import {
  defineConfig,
  envField,
  passthroughImageService,
  svgoOptimizer
} from 'astro/config';
import { unified } from '@astrojs/markdown-remark';
import react from '@astrojs/react';
import icon from 'astro-icon';
import editableRegions from '@cloudcannon/editable-regions/astro-integration';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import AstroPWA from '@vite-pwa/astro';

import tailwindcss from '@tailwindcss/vite';
import RouteData from './data/routing.json';
// Generated by tools/seo/url-history.mjs — one 301 for every URL any content
// entry has ever produced, so an edited slug cannot silently orphan its old
// URL. Hand-written rules in routing.json are applied last and win on conflict.
import UrlHistory from './data/url-history.json';
import rehypeExternalLinks, { type Options } from 'rehype-external-links';
import type { ValidRedirectStatus } from 'astro';
import { writeFile } from 'fs/promises';
import path from 'path';
import pagefind from 'astro-pagefind';

import { isInternalDomain } from './utils/domains';

const externalLinksConfig = {
  target: '_blank',
  rel: ['nofollow', 'noopener', 'noreferrer'],
  test: (node: any) => {
    try {
      const url = node.properties?.href;
      return typeof url === 'string' && !isInternalDomain(url);
    } catch {
      return false;
    }
  }
} satisfies Options;

type RedirectRule = {
  from: string;
  destination: string;
  status: ValidRedirectStatus;
};

/**
 * Netlify applies the first matching rule in _redirects, so precedence is
 * expressed by order: hand-written rules from routing.json come first and win,
 * generated history fills in behind them. Deduplication is by `from` alone —
 * two rules for the same source are a conflict, not two useful rules.
 */
function removeDuplicateRedirects(redirects: RedirectRule[]) {
  const seen = new Set<string>();
  const uniqueRedirects: RedirectRule[] = [];

  for (const redirect of redirects) {
    if (seen.has(redirect.from)) continue;
    seen.add(redirect.from);
    uniqueRedirects.push(redirect);
  }
  return uniqueRedirects;
}

// Generate denylist patterns from routing.json to exclude redirect paths from navigateFallback
const redirectDenylist = RouteData.routes.map((route) => {
  // Escape special regex characters and create exact match pattern
  const escapedPath = route.from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`^${escapedPath}$`);
});

// function convertJson(inputJson: {
//   routes: { from: string; destination: string; status: ValidRedirectStatus }[];
// }): Record<string, RedirectConfig> {
//   const result = new Map<string, RedirectConfig>();

//   removeDuplicateRedirects(inputJson.routes).forEach((route) => {
//     result.set(route.from, {
//       destination: route.destination,
//       status: route.status
//     });
//   });

//   return Object.fromEntries(result);
// }

// https://astro.build/config
export default defineConfig({
  site: 'https://topbiketoursportugal.com',
  integrations: [
    {
      name: 'NetliflyRedirects',
      hooks: {
        'astro:build:done': async ({ dir: _ }) => {
          const manual = (RouteData as { routes: RedirectRule[] }).routes;
          const generated = (UrlHistory as { routes: RedirectRule[] }).routes;

          const redirectsRules = removeDuplicateRedirects([
            ...manual,
            ...generated
          ]);

          const encodePath = (value: string) =>
            value
              .split('/')
              .map((segment) => encodeURI(segment))
              .join('/');

          const maxLength = Math.max(
            ...redirectsRules.map(({ from }) => encodePath(from).length)
          );

          const textRedirects = redirectsRules
            .map(
              ({ from, destination, status }) =>
                `${encodePath(from).padEnd(maxLength, ' ')} ${destination} ${status ?? 301}`
            )
            .join('\n');

          const redirectsPath = path.resolve('./dist', '_redirects');
          await writeFile(redirectsPath, `${textRedirects}\n`, 'utf8');

          console.log(
            `✅ _redirects generated — ${manual.length} hand-written + ` +
              `${generated.length} from URL history = ${redirectsRules.length} rules`
          );
        }
      }
    },
    // sentry(),
    // spotlightjs(),
    // astroMetaTags(),
    react(),
    editableRegions(),
    // Heroicons SVG set in src/icons, used by the starter components' <Icon>.
    icon(),
    // svgs({
    //   input: [
    //     'src/assets/icons/ph/light',
    //     'src/assets/icons/ph/fill',
    //     'src/assets/icons/logos',
    //     'src/assets/icons/fa',
    //     'src/assets/icons/circle-flags'
    //   ]
    // }),

    // v7: markdown/MDX plugins now live on `markdown.processor` (unified());
    // MDX inherits them via extendMarkdownConfig, so `mdx()` takes no plugins.
    mdx(),
    AstroPWA({
      mode: 'production',
      base: '/',
      scope: '/',
      registerType: 'autoUpdate',
      manifest: {
        name: 'Top Bike Tours Portugal',
        short_name: 'TBTP',
        description: 'Top Bike Tours Portugal',
        theme_color: '#ff7700',
        background_color: '#fff',
        display: 'standalone',
        icons: [
          {
            src: '/favicon-16.png',
            sizes: '16x16',
            type: 'image/png'
          },
          {
            src: '/favicon-32.png',
            sizes: '32x32',
            type: 'image/png'
          },
          {
            src: '/favicon-16.png',
            sizes: '16x16',
            type: 'image/png'
          },
          {
            src: '/favicon-48.png',
            sizes: '48x48',
            type: 'image/png'
          },
          {
            src: '/favicon-128.png',
            sizes: '128x128',
            type: 'image/png'
          },
          {
            src: '/favicon-512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      },
      workbox: {
        navigateFallback: '/404/',
        navigateFallbackDenylist: redirectDenylist,
        globPatterns: ['**/*.{css,js,html,avif,ico}'],
        // The CloudCannon editor-only registration bundle (eager glob of every
        // component) is ~14 MB and only loads inside the Visual Editor —
        // never precache it. Keep the node_modules default when overriding.
        globIgnores: ['**/node_modules/**/*', '**/registerComponents.*.js'],
        runtimeCaching: [
          {
            urlPattern: ({ request }) => request.mode === 'navigate',
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'pages',
              expiration: {
                maxEntries: 50,
                maxAgeSeconds: 30 * 24 * 60 * 60 // 30 days
              }
            }
          }
        ]
      },
      devOptions: {
        enabled: false
      }
    }),
    // shield({}),
    // playformInline()
    // min()
    // playformCompress({
    //   CSS: true,
    //   HTML: false,
    //   Image: false,
    //   JavaScript: false,
    //   SVG: true,
    //   Logger: 0
    // })
    sitemap({
      // filter: (page) => !redirects.has(page),
      i18n: {
        defaultLocale: 'en', // All urls that don't contain `es` or `fr` after `https://stargazers.club/` will be treated as default locale, i.e. `en`
        locales: {
          en: 'en-US', // The `defaultLocale` value must present in `locales` keys
          pt: 'pt-PT'
        }
      }
    }),
    pagefind()
  ],
  markdown: {
    // v7: the Rust "Satteri" markdown processor is the default, and top-level
    // `rehypePlugins` no-op under it. Opt back into the unified pipeline so
    // rehype-external-links keeps running on both .md and (inherited) MDX.
    processor: unified({
      rehypePlugins: [[rehypeExternalLinks, externalLinksConfig]]
    })
  },
  // redirects: convertJson(
  //   RouteData as {
  //     routes: {
  //       from: string;
  //       destination: string;
  //       status: ValidRedirectStatus;
  //     }[];
  //   }
  // ),
  prefetch: {
    defaultStrategy: 'viewport'
  },
  env: {
    schema: {
      GOOGLE_SITE_VERIFICATION_ID: envField.string({
        context: 'client',
        access: 'public',
        optional: true
      }),
      GOOGLE_TAG_MANAGER_ID: envField.string({
        context: 'client',
        access: 'public',
        optional: true,
        default: 'GTM-KRC3B4ZQ'
      }),
      GOOGLE_ANALYTICS_ID: envField.string({
        context: 'client',
        access: 'public',
        optional: true,
        default: '385531271'
      }),
      GOOGLE_PUBLIC_CAPTCHA: envField.string({
        context: 'client',
        access: 'public',
        optional: true
      }),
      SITE_URL: envField.string({
        context: 'client',
        access: 'public',
        default: 'https://topbiketoursportugal.com'
      }),
      INDEX: envField.string({
        context: 'client',
        access: 'public',
        default: 'true'
      })
      // API_SECRET: envField.string({ context: "server", access: "secret" }),
    }
  },
  i18n: {
    locales: ['en', 'pt'],
    defaultLocale: 'en',
    routing: {
      // v6: `redirectToDefaultLocale` only applies when `prefixDefaultLocale` is true.
      // With prefixDefaultLocale:false the default locale has no prefix, so there is
      // nothing to redirect — the option is dropped to satisfy v6 validation.
      prefixDefaultLocale: false
    }
  },
  trailingSlash: 'ignore',

  experimental: {
    // v6.2+: SVGO optimization moved from `svgo: true` to a pluggable optimizer.
    // Optimizes SVGs imported as Astro components (e.g. Footer's biosphere/atta logos).
    svgOptimizer: svgoOptimizer()
    // csp: {
    //   // change the default algorithm
    //   algorithm: "SHA-512",
    //   // insert additional directives
    //   directives: [
    //     "default-src: 'self'",
    //   ],
    //   // add more information to the `style-src` directive
    //   styleDirective: {
    //     hashes: [
    //       "sha384-somehash" // hash generated for some external style e.g. white label, etc.
    //     ],
    //     // **Override** default resources
    //     resources: ["self"]
    //   },

    //   // add more information to the `style-src` directive
    //   scriptDirective: {
    //     hashes: [
    //       "sha384-somehash" // hash generated for some external script e.g. analytics, jQuery, etc.
    //     ],
    //     // **Override** default resources
    //     resources: ["self"],
    //     // Toggle the keyword `strict-dynamic`
    //     strictDynamic: true
    //   }
    // }
  },
  image: {
    service:
      process.env.NODE_ENV === 'production'
        ? { entrypoint: 'astro/assets/services/sharp' }
        : passthroughImageService()
  },

  // redirects: {
  //   '/[...path]': '/[...path]/'
  // }
  vite: {
    plugins: [tailwindcss() as any],
    resolve: {
      // Aliases used by the components imported from CloudCannon's
      // astro-component-starter (mirrors that repo's alias map).
      alias: {
        // astro-icon → @iconify/utils imports the CJS `debug` package, which
        // the dev server serves raw ("does not provide an export named
        // 'default'") when reached from client code — the editor-only
        // registerComponents bundle does exactly that, and the failure
        // disables ALL visual editing in dev. `debug` is just a logger;
        // shim it.
        'debug': path.resolve('./src/cloudcannon/debug-shim.mjs'),
        '@components': path.resolve('./src/components'),
        '@component-utils': path.resolve('./src/components/utils'),
        '@core-elements': path.resolve(
          './src/components/building-blocks/core-elements'
        ),
        '@forms': path.resolve('./src/components/building-blocks/forms'),
        '@wrappers': path.resolve('./src/components/building-blocks/wrappers'),
        '@page-sections': path.resolve('./src/components/page-sections'),
        '@builders': path.resolve('./src/components/page-sections/builders'),
        '@features': path.resolve('./src/components/page-sections/features')
      }
    }
  }
});
