# src/components/two-column-markdown/two-column-markdown.bookshop.yml
spec:
  structures:
    - content_blocks # or any structure you are using
  label: Text Markdown
  description: Displays content Markdown.
  icon: text # Choose an appropriate icon
  tags:
    - Markdown
    - Text

blueprint:
  text: |
    ## Column 1

    Enter your Markdown content here.
  style:
    container: full
    padding: normal
    align: centered
    tailwind:
preview:

_inputs:
  text:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      blockquote: true
      bold: true
      bulletedlist: true
      code: true
      copyformatting: true
      embed: true
      format: p h1 h2 h3 h4
      horizontalrule: true
      image: true
      image_size_attributes: true
      italic: true
      link: true
      numberedlist: true
      redo: true
      removeformat: true
      strike: true
      subscript: true
      superscript: true
      table: true
      underline: true
      undo: true
  padding:
    options:
      values:
        - name: Tight
          value: tight
        - name: Normal
          value: normal
        - name: Loose
          value: loose
      preview:
        icon: 'short_text'
        text:
          - key: style.padding
  container:
    options:
      values:
        - name: Full
          value: full
        - name: Centered
          value: centered
      preview:
        icon: 'short_text'
        text:
          - key: style.container
  align:
    options:
      values:
        - name: Leading
          value: leading
        - name: Trailing
          value: trailing
        - name: Centered
          value: centered
      value_key: value
      preview:
        icon: 'short_text'
        text:
          - key: style.layout
