#!/usr/bin/env bash

# npx @bookshop/generate@3.17.1 || echo "Warning: Bookshop generate encountered errors (non-fatal)"
# npx @divriots/jampack ./dist
# npx html-minifier --input-dir ./dist --output-dir ./dist --file-ext html --collapse-whitespace --minify-js