# src/components/two-column-markdown/two-column-markdown.bookshop.yml
spec:
  structures:
    - content_blocks # or any structure you are using
  label: Two Column Markdown
  description: Displays content in two columns using Markdown.
  icon: columns # Choose an appropriate icon
  tags:
    - Markdown
    - Layout

blueprint:
  column1: |
    ## Column 1

    Enter your Markdown content here.
  column2: |
    ## Column 2

    Enter your Markdown content here.
  padding: 'normal'
  fullwidth: true

# preview:
#   fullwidth: false
#   padding: normal
#   column1: |
#     ## Column 1

#     This is some **Markdown** content for the first column.
#   column2: |
#     ## Column 2

#     This is some **Markdown** content for the first column.

_inputs:
  column1:
    type: markdown
  column2:
    type: markdown
  fullwidth:
    type: boolean
  padding:
    type: select
    options:
      - contained
      - tight
      - normal
