# src/components/two-column-markdown/two-column-markdown.bookshop.yml
spec:
  structures:
    - content_blocks # or any structure you are using
  label: Two Column Markdown
  description: Displays content in two columns using Markdown.
  icon: columns # Choose an appropriate icon
  tags:
    - Markdown
    - Layout

blueprint:
  column1: |
    ## Column 1

    Enter your Markdown content here.
  column2: |
    ## Column 2

    Enter your Markdown content here.
  padding: 'normal'
  fullwidth: true

# preview:
#   fullwidth: false
#   padding: normal
#   column1: |
#     ## Column 1

#     This is some **Markdown** content for the first column.
#   column2: |
#     ## Column 2

#     This is some **Markdown** content for the first column.

_inputs:
  column1:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      blockquote: true
      bold: true
      bulletedlist: true
      code: true
      copyformatting: true
      embed: true
      format: p h1 h2 h3 h4
      horizontalrule: true
      image: true
      image_size_attributes: true
      italic: true
      link: true
      numberedlist: true
      redo: true
      removeformat: true
      strike: true
      subscript: true
      superscript: true
      table: true
      underline: true
      undo: true
  column2:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      blockquote: true
      bold: true
      bulletedlist: true
      code: true
      copyformatting: true
      embed: true
      format: p h1 h2 h3 h4
      horizontalrule: true
      image: true
      image_size_attributes: true
      italic: true
      link: true
      numberedlist: true
      redo: true
      removeformat: true
      strike: true
      subscript: true
      superscript: true
      table: true
      underline: true
      undo: true
  fullwidth:
    type: switch
  padding:
    type: select
    options:
      - contained
      - tight
      - normal
