import {
  defineConfig,
  envField,
  fontProviders,
  passthroughImageService,
  svgoOptimizer
} from 'astro/config';
import { satteri } from '@astrojs/markdown-satteri';
import react from '@astrojs/react';
import icon from 'astro-icon';
import editableRegions from '@cloudcannon/editable-regions/astro-integration';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import AstroPWA from '@vite-pwa/astro';

import tailwindcss from '@tailwindcss/vite';
import RouteData from './data/routing.json';
// Generated by `pnpm seo:urls` (@ttp/seo-tools/url-history.mjs) — one 301 for every URL any contents
// entry has ever produced, so an edited slug cannot silently orphan its old
// URL. Hand-written rules in routing.json are applied last and win on conflict.
import UrlHistory from './data/url-history.json';
import { lastmodFor } from '@ttp/seo-tools/lib/lastmod.mjs';
import {
  alternatesFor,
  LOCALES,
  DEFAULT_LOCALE
} from '@ttp/seo-tools/lib/alternates.mjs';
import { noindexPathSet } from '@ttp/seo-tools/lib/routes.mjs';
import type { ValidRedirectStatus } from 'astro';
import { writeFile } from 'fs/promises';
import path from 'path';
import pagefind from 'astro-pagefind';

import { satteriExternalLinks } from './utils/satteri-external-links';

type RedirectRule = {
  from: string;
  destination: string;
  status: ValidRedirectStatus;
};

/**
 * Paths whose page renders `noindex`, read once from content frontmatter and
 * used by the sitemap filter below.
 */
const NOINDEX_PATHS: Set<string> = noindexPathSet();

/**
 * Netlify applies the first matching rule in _redirects, so precedence is
 * expressed by order: hand-written rules from routing.json come first and win,
 * generated history fills in behind them. Deduplication is by `from` alone —
 * two rules for the same source are a conflict, not two useful rules.
 */
function removeDuplicateRedirects(redirects: RedirectRule[]) {
  const seen = new Set<string>();
  const uniqueRedirects: RedirectRule[] = [];

  for (const redirect of redirects) {
    if (seen.has(redirect.from)) continue;
    seen.add(redirect.from);
    uniqueRedirects.push(redirect);
  }
  return uniqueRedirects;
}

// Generate denylist patterns from routing.json to exclude redirect paths from navigateFallback
const redirectDenylist = RouteData.routes.map((route) => {
  // Escape special regex characters and create exact match pattern
  const escapedPath = route.from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`^${escapedPath}$`);
});

// function convertJson(inputJson: {
//   routes: { from: string; destination: string; status: ValidRedirectStatus }[];
// }): Record<string, RedirectConfig> {
//   const result = new Map<string, RedirectConfig>();

//   removeDuplicateRedirects(inputJson.routes).forEach((route) => {
//     result.set(route.from, {
//       destination: route.destination,
//       status: route.status
//     });
//   });

//   return Object.fromEntries(result);
// }

// https://astro.build/config
export default defineConfig({
  site: 'https://topbiketoursportugal.com',
  integrations: [
    {
      name: 'NetliflyRedirects',
      hooks: {
        'astro:build:done': async ({ dir: _ }) => {
          const manual = (RouteData as { routes: RedirectRule[] }).routes;
          const generated = (UrlHistory as { routes: RedirectRule[] }).routes;

          const redirectsRules = removeDuplicateRedirects([
            ...manual,
            ...generated
          ]);

          const encodePath = (value: string) =>
            value
              .split('/')
              .map((segment) => encodeURI(segment))
              .join('/');

          const maxLength = Math.max(
            ...redirectsRules.map(({ from }) => encodePath(from).length)
          );

          const textRedirects = redirectsRules
            .map(
              ({ from, destination, status }) =>
                `${encodePath(from).padEnd(maxLength, ' ')} ${destination} ${status ?? 301}`
            )
            .join('\n');

          const redirectsPath = path.resolve('./dist', '_redirects');
          await writeFile(redirectsPath, `${textRedirects}\n`, 'utf8');

          console.log(
            `✅ _redirects generated — ${manual.length} hand-written + ` +
              `${generated.length} from URL history = ${redirectsRules.length} rules`
          );
        }
      }
    },
    // sentry(),
    // spotlightjs(),
    // astroMetaTags(),
    react(),
    editableRegions(),
    // Heroicons SVG set in src/icons, used by the starter components' <Icon>.
    icon(),
    // svgs({
    //   input: [
    //     'src/assets/icons/ph/light',
    //     'src/assets/icons/ph/fill',
    //     'src/assets/icons/logos',
    //     'src/assets/icons/fa',
    //     'src/assets/icons/circle-flags'
    //   ]
    // }),

    // v7: markdown/MDX plugins now live on `markdown.processor` (unified());
    // MDX inherits them via extendMarkdownConfig, so `mdx()` takes no plugins.
    mdx(),
    AstroPWA({
      mode: 'production',
      base: '/',
      scope: '/',
      registerType: 'autoUpdate',
      manifest: {
        name: 'Top Bike Tours Portugal',
        short_name: 'TBTP',
        description: 'Top Bike Tours Portugal',
        theme_color: '#ff7700',
        background_color: '#fff',
        display: 'standalone',
        icons: [
          {
            src: '/favicon-16.png',
            sizes: '16x16',
            type: 'image/png'
          },
          {
            src: '/favicon-32.png',
            sizes: '32x32',
            type: 'image/png'
          },
          {
            src: '/favicon-16.png',
            sizes: '16x16',
            type: 'image/png'
          },
          {
            src: '/favicon-48.png',
            sizes: '48x48',
            type: 'image/png'
          },
          {
            src: '/favicon-128.png',
            sizes: '128x128',
            type: 'image/png'
          },
          {
            src: '/favicon-512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      },
      workbox: {
        // No trailing slash: @vite-pwa/astro rewrites `404.html` in the
        // precache manifest to `404` + (trailingSlash === 'always' ? '/' : ''),
        // and this site is `trailingSlash: 'ignore'`. Asking for '/404/' looked
        // up a key that is not in the manifest, so `createHandlerBoundToURL`
        // threw `non-precached-url` while sw.js was still evaluating — which
        // aborted the rest of the service worker setup, not just the fallback.
        navigateFallback: '/404',
        navigateFallbackDenylist: redirectDenylist,
        globPatterns: ['**/*.{css,js,html,avif,ico}'],
        // The CloudCannon editor-only registration bundle (eager glob of every
        // component) is ~14 MB and only loads inside the Visual Editor —
        // never precache it. Keep the node_modules default when overriding.
        globIgnores: ['**/node_modules/**/*', '**/registerComponents.*.js'],
        runtimeCaching: [
          {
            urlPattern: ({ request }) => request.mode === 'navigate',
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'pages',
              expiration: {
                maxEntries: 50,
                maxAgeSeconds: 30 * 24 * 60 * 60 // 30 days
              }
            }
          }
        ]
      },
      devOptions: {
        enabled: false
      }
    }),
    // playformInline()
    // min()
    // playformCompress({
    //   CSS: true,
    //   HTML: false,
    //   Image: false,
    //   JavaScript: false,
    //   SVG: true,
    //   Logger: 0
    // })
    sitemap({
      // Keep noindex URLs out of the sitemap. Advertising a URL for crawling
      // while its own page says `noindex` is a contradictory signal;
      // `/thank-you-page/` shipped both for months. Derived from
      // `seo.no_index` in the content rather than hand-listed, so a page that
      // gets the flag later drops out of the sitemap on the next build.
      filter: (page) => {
        const { pathname } = new URL(page);
        return !NOINDEX_PATHS.has(pathname);
      },
      // Stamp each content-backed URL with the date of the commit that last
      // touched it. Without this Google has no reason to recrawl a page it
      // indexed months ago — which is why renamed tours kept their old titles
      // in the SERP long after the rewrite.
      serialize(item) {
        const lastmod = lastmodFor(item.url);
        // `i18n` below pairs translations by path, which only works for the
        // routes with no translated slug. Every content-backed URL is paired
        // by source file instead — see @ttp/seo-tools/lib/alternates.mjs. `links`
        // is assigned unconditionally: it has to be able to clear what `i18n`
        // matched, not only add to it.
        return {
          ...item,
          links: alternatesFor(item.url, item.links),
          ...(lastmod ? { lastmod } : {})
        };
      },
      i18n: {
        defaultLocale: DEFAULT_LOCALE, // All urls that don't contain `pt` after `https://topbiketoursportugal.com/` will be treated as default locale, i.e. `en`
        locales: LOCALES // The `defaultLocale` value must be present in `locales` keys
      }
    }),
    pagefind()
  ],
  markdown: {
    // Sätteri, Astro's native (Rust) pipeline and the v7 default. The config
    // previously opted back into `unified()` purely because top-level
    // `rehypePlugins` no-op under Sätteri, so rehype-external-links stopped
    // running. Sätteri exposes the same hast via `hastPlugins`, so that rule
    // now lives in utils/satteri-external-links.ts and the site runs on the
    // faster processor instead of paying for the JS pipeline to keep it.
    processor: satteri({
      hastPlugins: [satteriExternalLinks()]
    })
  },
  // redirects: convertJson(
  //   RouteData as {
  //     routes: {
  //       from: string;
  //       destination: string;
  //       status: ValidRedirectStatus;
  //     }[];
  //   }
  // ),
  prefetch: {
    defaultStrategy: 'viewport'
  },
  env: {
    schema: {
      GOOGLE_SITE_VERIFICATION_ID: envField.string({
        context: 'client',
        access: 'public',
        optional: true
      }),
      GOOGLE_TAG_MANAGER_ID: envField.string({
        context: 'client',
        access: 'public',
        optional: true,
        default: 'GTM-KRC3B4ZQ'
      }),
      GOOGLE_ANALYTICS_ID: envField.string({
        context: 'client',
        access: 'public',
        optional: true,
        default: '385531271'
      }),
      GOOGLE_PUBLIC_CAPTCHA: envField.string({
        context: 'client',
        access: 'public',
        optional: true
      }),
      SITE_URL: envField.string({
        context: 'client',
        access: 'public',
        default: 'https://topbiketoursportugal.com'
      }),
      INDEX: envField.string({
        context: 'client',
        access: 'public',
        default: 'true'
      })
      // API_SECRET: envField.string({ context: "server", access: "secret" }),
    }
  },
  i18n: {
    locales: Object.keys(LOCALES),
    defaultLocale: 'en',
    routing: {
      // v6: `redirectToDefaultLocale` only applies when `prefixDefaultLocale` is true.
      // With prefixDefaultLocale:false the default locale has no prefix, so there is
      // nothing to redirect — the option is dropped to satisfy v6 validation.
      prefixDefaultLocale: false
    }
  },
  trailingSlash: 'ignore',

  // Self-hosted via the same @fontsource-variable packages as before, but
  // routed through Astro so it can emit `<link rel="preload">` and generate
  // metric-matched fallbacks. Previously these were plain CSS `@import`s, which
  // meant no page carried a single font preload: the browser found the woff2
  // only after fetching a ~294 KB render-blocking stylesheet, and the
  // hand-guessed fallback stack shifted layout on swap.
  //
  // `npm({ remote: false })` resolves from the locally installed packages, so
  // the build stays offline and reproducible — no CDN fetch at build time.
  //
  // `weights` MUST be the variable range, not a single value: it defaults to
  // [400] only, which would silently synthesise bold headings instead of using
  // the real upper masters. Ranges below match each package's own metadata.
  // `styles` is normal-only — the codebase uses no italics — which also drops
  // Figtree's unused italic files.
  fonts: [
    {
      provider: fontProviders.npm({ remote: false }),
      name: 'Figtree Variable',
      cssVariable: '--font-figtree',
      weights: ['300 900'],
      styles: ['normal'],
      subsets: ['latin', 'latin-ext'],
      fallbacks: ['ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif']
    },
    {
      provider: fontProviders.npm({ remote: false }),
      name: 'Bricolage Grotesque Variable',
      cssVariable: '--font-bricolage',
      weights: ['200 800'],
      styles: ['normal'],
      subsets: ['latin', 'latin-ext'],
      fallbacks: ['ui-sans-serif', 'system-ui', 'sans-serif']
    },
    {
      provider: fontProviders.npm({ remote: false }),
      name: 'Caveat Variable',
      cssVariable: '--font-caveat-family',
      weights: ['400 700'],
      styles: ['normal'],
      // Latin only: the package also ships Cyrillic masters, ~116 KB that no
      // locale on this site (en/pt/de/es/fr/nl) can use.
      subsets: ['latin', 'latin-ext'],
      fallbacks: ['Comic Sans MS', 'cursive']
    }
  ],

  // Two routes generating the same URL is a silent content bug, not a style
  // question: the loser is dropped and its page simply never ships. That is how
  // `/blog` was lost for six locales — the catch-all `[...path]` route mapped
  // the whole `pages` collection, including the paginated blog index that
  // `blog/[...page]` already owns, and the warning scrolled past on every
  // build. The catch-all still maps a CMS-authored collection, so an editor can
  // recreate the collision from CloudCannon without touching code; `error`
  // makes that a failed build instead of a quietly missing page. Also applies
  // to duplicate content-collection entry IDs, which matters across 540
  // translated posts.
  prerenderConflictBehavior: 'error',

  experimental: {
    // v6.2+: SVGO optimization moved from `svgo: true` to a pluggable optimizer.
    // Optimizes SVGs imported as Astro components (e.g. Footer's biosphere/atta logos).
    svgOptimizer: svgoOptimizer()
    // NB: CSP is NOT an experimental option — it moved to top-level
    // `security.csp` in v6, and `experimental` is a strict schema, so putting
    // a `csp` key here fails config validation rather than being ignored.
    // Native CSP is also a poor fit for this site: it is unsupported alongside
    // `<ClientRouter />` (used in Layout.astro) without warning, it cannot hash
    // the 25 `is:inline` scripts (GTM, cookie consent, forms, JSON-LD), and
    // jampack rewrites the HTML after the hashes are computed. The
    // report-only header in netlify.toml is the supported path here.
  },
  image: {
    service:
      process.env.NODE_ENV === 'production'
        ? {
            entrypoint: 'astro/assets/services/sharp',
            // Encoder defaults for images that do not pass their own `quality`
            // — chiefly core-elements/image/Image.astro, which is the bulk of
            // the build (~1300 webp). A per-image `quality` prop still wins
            // over anything here, which is why the AVIF fix lives in
            // ResponsiveImage.astro instead of in this block.
            //
            // `effort` is deliberately left at sharp's default: raising it to 6
            // roughly doubled a single AVIF encode for ~3% fewer bytes, which
            // across the image set costs far more build time than it is worth.
            config: {
              avif: { quality: 80 },
              webp: { quality: 80 },
              // `mozjpeg: true` was measured and dropped: it applies to only
              // 187 transformed JPEGs totalling ~21 MB, and cost roughly a
              // 10x slowdown per encode for a fraction of that. `progressive`
              // is free and improves perceived load.
              jpeg: { quality: 80, progressive: true },
              // Default compressionLevel is 6; 9 is a solid win on the
              // screenshot-style PNGs and only 36 files take this path.
              png: { compressionLevel: 9 }
            }
          }
        : passthroughImageService()
  },

  // redirects: {
  //   '/[...path]': '/[...path]/'
  // }
  vite: {
    // `@tailwindcss/vite` and Astro resolve their own, structurally-mismatched
    // copies of vite's `Plugin` type in this dependency tree, so this cast is
    // load-bearing rather than laziness — TS otherwise rejects a plugin that
    // works fine at runtime.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    plugins: [tailwindcss() as any],
    resolve: {
      // Aliases used by the components imported from CloudCannon's
      // astro-component-starter (mirrors that repo's alias map).
      alias: {
        // astro-icon → @iconify/utils imports the CJS `debug` package, which
        // the dev server serves raw ("does not provide an export named
        // 'default'") when reached from client code — the editor-only
        // registerComponents bundle does exactly that, and the failure
        // disables ALL visual editing in dev. `debug` is just a logger;
        // shim it.
        'debug': path.resolve('./src/cloudcannon/debug-shim.mjs'),
        '@components': path.resolve('./src/components'),
        '@component-utils': path.resolve('./src/components/utils'),
        '@core-elements': path.resolve(
          './src/components/building-blocks/core-elements'
        ),
        '@forms': path.resolve('./src/components/building-blocks/forms'),
        '@wrappers': path.resolve('./src/components/building-blocks/wrappers'),
        '@page-sections': path.resolve('./src/components/page-sections'),
        '@builders': path.resolve('./src/components/page-sections/builders'),
        '@features': path.resolve('./src/components/page-sections/features')
      }
    }
  }
});
