# tour-card.bookshop.yml
name: Tour Card
icon: card_membership
description: A card component for displaying tour information.

# Define the component file
components:
  - path: src/components/tour-card.astro

# Define the props/fields that can be edited in CloudCannon
blueprint:
  tour:
    type: reference
    collection: tours
    preview: title
    required: true
    help_text: Select a tour from the tours collection to display.
  language:
    type: select
    options:
      - value: en
        label: English
      - value: es
        label: Spanish
      - value: fr
        label: French
      # Add more languages as needed based on your Languages JSON
    default: en
    required: true
    help_text: Choose the language for formatting prices and content.
  contentDisplay:
    type: select
    options:
      - value: inline
        label: Inline
      - value: block
        label: Block
    default: inline
    help_text: Controls how the card content is displayed.

# Define how the component previews in CloudCannon
preview:
  tour:
    _default:
      title: Sample Tour
      image:
        src: https://via.placeholder.com/300x200
        alt: Sample Tour Image
      content:
        This is a sample tour description. Lorem ipsum dolor sit amet,
        consectetur adipiscing elit.
      duration: 7
      tags:
        - Adventure
        - Nature
      packages:
        - price:
            price: 1200
            promo: 1000
            currency: EUR
    language: en
    contentDisplay: inline

# Optional: Define inputs for the referenced 'tours' collection (if needed)
collections_config:
  tours:
    path: src/content/tours
    output: true
    schemas:
      default:
        path: .cloudcannon/schemas/tour.md
        fields:
          title:
            type: string
            required: true
          image:
            type: object
            fields:
              src:
                type: url
                required: true
              alt:
                type: string
          content:
            type: markdown
          duration:
            type: number
            help_text: Duration in days
          tags:
            type: list
            allow_add: true
          packages:
            type: list
            allow_add: true
            fields:
              price:
                type: object
                fields:
                  price:
                    type: number
                  promo:
                    type: number
                  currency:
                    type: string
                    default: EUR
