# faq-accordion.bookshop.yml
name: FAQ Accordion
icon: expand_more
description: An accordion component for displaying frequently asked questions.

# Define the component file
components:
  - path: src/components/faq-accordion.astro

# Define the props/fields that can be edited in CloudCannon
blueprint:
  language:
    type: select
    options:
      - value: en
        label: English
      - value: pt
        label: Portuguese
      # Add more languages as needed based on your faqs.json
    default: en
    required: true
    help_text: Choose the language for the FAQs.
  faqs:
    type: list
    allow_add: true
    help_text:
      Add custom FAQs. Leave empty to use default FAQs for the selected
      language.
    fields:
      question:
        type: string
        required: true
        help_text: The question to display in the accordion header.
      answer:
        type: markdown
        required: true
        help_text: The answer content in markdown format.

# Define how the component previews in CloudCannon
preview:
  language: en
  faqs:
    - question: What is the duration of the tour?
      answer: The tour lasts 7 days and 6 nights.
    - question: What is included in the price?
      answer: The price includes accommodation, meals, and guided tours.

# Optional: Define inputs for default FAQs data (if managed externally)
inputs:
  faqs_json:
    type: file
    path: src/data/faqs.json
    comment: JSON file containing default FAQs for each language.
    help_text: Edit the default FAQs for all languages in src/data/faqs.json.
