# itinerary-accordion.bookshop.yml
name: Itinerary Accordion
icon: list_alt
description:
  An accordion component for displaying an itinerary with titles and
  descriptions.

# Define the component file
components:
  - path: src/components/itinerary-accordion.astro

# Define the props/fields that can be edited in CloudCannon
blueprint:
  itinerary:
    type: list
    allow_add: true
    help_text: Add itinerary items with a title and optional description.
    fields:
      title:
        type: markdown
        required: true
        help_text:
          The title of the itinerary item, displayed in the accordion header.
      description:
        type: markdown
        help_text: The description content in markdown format (optional).~
      location:
        type: object
        structures: _structures.location
# Define how the component previews in CloudCannon
preview:
  itinerary:
    - title: 'Day 1: Arrival'
      description: Arrive at the destination and check into your hotel.
      location:
        location:
        lat: '1'
        lng: '1'
        country: pt
        region: ''
        city: ''
    - title: 'Day 2: City Tour'
      description: Explore the city with a guided tour of major landmarks.
      location:
    - title: 'Day 3: Departure'
      description: Check out and depart for your next destination.
      location:
