# src/components/two-column-markdown/two-column-markdown.bookshop.yml
spec:
  structures:
    - content_blocks # or any structure you are using
  label: Timeline
  description: Timeline
  icon: text # Choose an appropriate icon
  tags:
    - Markdown
    - Text

blueprint:
  dates:
    - date: 2015-01-01
      title: New date for guided tour title
      subtitle: New date for guided tour title
      description: New date for guided tour description
  style:
    container: centered
    padding: normal
# structures:

_inputs:
  padding:
    options:
      values:
        - name: Tight
          value: tight
        - name: Normal
          value: normal
        - name: Loose
          value: loose
      preview:
        icon: 'short_text'
        text:
          - key: style.padding
  container:
    options:
      values:
        - name: Full
          value: full
        - name: Centered
          value: centered
      preview:
        icon: 'short_text'
        text:
          - key: style.container
  dates:
    type: array
  dates[*].date:
    type: date
  dates[*].title:
    type: markdown
  dates[*].subtitle:
    type: markdown
  dates[*].description:
    type: markdown
