# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Collection
  description: Text next to image with button
  icon: 'chrome_reader_mode'
  tags:
    - Text
    - Image
    - Button
    - Flippable

# Defines the structure of this component, as well as the default values
blueprint:
  type: 'tours' #| 'reviews' | 'team' | 'bikes' | 'posts';
  # display: 'list'
  # contentDisplay: 'inline'
  # frame: 'none'
  # layout: 'horizontal'
  title: Collection Title

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  type: select
  hidden: false
  options:
    allow_empty: false
    values:
      - tours
      - reviews
      - team
      # -  bikes
      - posts
