# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Collection
  description: Text next to image with button
  icon: 'chrome_reader_mode'
  tags:
    - Text
    - Image
    - Button
    - Flippable

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#ffffff'
  heading:
    heading_text: Keep what you need. Delete the rest.
    color: '#393939'
  text:
    animation: slide-in
    markdown_content: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
    color: '#393939'
  image:
    image_path: /src/assets/images/undraw-hello.svg
    alt_text: An image
    pharalax: true
  flipped: true
  button: bookshop:structure:buttons
  style:
    align: leading
    distribution: stretch
    orientation: horizontal
    container: full

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  layout:
    options:
      values:
        - name: Leading
          value: leading
        - name: Trailing
          value: trailing
      value_key: value
      preview:
        icon: 'short_text'
        text:
          - key: style.layout
  distribution:
    default: stretch
    options:
      preview:
        icon: 'short_text'
        text:
          - key: style.distribution
      values:
        - name: Stretch
          value: stretch
        - name: Space Evenly
          value: spaceEvenly
      value_key: value
  orientation:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: style.orientation
      values:
        - name: Horizontal
          value: horizontal
        - name: Vertical
          value: vertical
      value_key: value
  container:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: style.container
      values:
        - name: Full
          value: full
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
        - name: Extra Large
          value: xl
        - name: Extra Extra Large
          value: 2xl
      value_key: value
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Heading
        subtext:
          - key: heading_gradient_color
          - 'Update heading gradient color and text content.'
  text:
    options:
      preview:
        icon: 'edit_note'
        text:
          - Text
        subtext:
          - 'Update text content and color.'
  image:
    options:
      preview:
        icon: 'image'
        text:
          - key: alt_text
          - 'Image'
        subtext:
          - key: image_path
          - 'Update image'
        image:
          - key: image_path
        # gallery:
        #   text:
        #     - key: alt_text
        #     - 'Image'
        #   image:
        #     - key: image_path
        #   icon: 'image'
  flipped:
    type: switch
