# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Featured testimonials/reviews
  description: Featured testimonials grid
  icon: 'message'
  tags:
    - Grid
    - Testimonials
    - Tours

# Defines the structure of this component, as well as the default values
blueprint:
  feature_testimonials: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text:
    - key: title
  subtext:
    - key: language
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  feature_testimonials:
    type: multiselect
    options:
      empty_type: array
      values: collections.testimonials
      value_key: id
      preview:
        text:
          - key: title
        subtext:
          - key: language
        icon: message
